database_names:
    Rico: rico_lipids
    Domenico: domenico_stem_cell
    Rik lipids: rik_lipids
db_root_path: //home/ricoderks/Documents/LUMC/Projects/omicser/examples/databases
conda_environment: .pyenv
install: configured
